name: Push to Master

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    name: Test, Build, Analysis And Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 2.2.104
    - name: Code Rebulild
      run: dotnet build SampleAPI.sln --no-incremental
    - name: Build the Docker Image
      run: docker build . --file ./SampleAPI.Code/Dockerfile --tag praveshchhabra/sampleapi
    - name: Login into Docker Hub
      run: docker login ${{ secrets.dockercred }}
    - name: Push the Docker Image
      run: docker push praveshchhabra/sampleapi
      
    
